config/routes.rb
Rails.application.routes.draw do

  resources :users do 

  resources :books 
end

   root 'users#index'
   resources :comments, only: [:create, :destroy]

end

app/models/add_likes_to_comment.rb
class AddLikesToComment < ActiveRecord::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
	validates :title, presence: true
	validates :author, presence: true

	has_many :comments, dependent: :destroy
	
	belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :comment, presence: true

	belongs_to :user
	belongs_to :book
	#has_many :likes
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, presence: true
	validates :username, presence: true, format: { without: /\s/ }, uniqueness:{ case_sensitive: false}

	has_many :comments, dependent: :destroy
	
	has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_User, only: [:show, :edit, :update, :destroy]

  def index
   @user = User.find(params[:user_id])
   @books = @user.books

  end

  def create
     user=User.find(params[:user_id])
     @book=user.books.new(permitted_params)
   if @book.save
        flash[:notice]= "A Book has been successfully added."
     redirect_to user_books_path

      else
        flash[:error] = @book.errors.full_messages.to_sentence
        redirect_to new_user_book_path 
      end
  end

  def new
    @user=User.find(params[:user_id])
    @book=Book.new
  end

  def show
  @user=User.find(params[:user_id])
  @comments = @book.comments
  @comment=Comment.new
  end

  def edit
   @user=User.find(params[:user_id])
  end

  def update
    @user=User.find(params[:user_id])
      if @book.update(permitted_params)        
          redirect_to user_books_path, notice: 'User was successfully updated.'
      else
        flash[:error] = @book.errors.full_messages.to_sentence
        redirect_to edit_user_book_path(@book)
      end
  end

  def destroy
    
    @book.destroy
     redirect_to user_books_path(@user)
  
  end

  private

  def load_User
    @book=Book.find(params[:id])
    @user=@book.user
  end

 def permitted_params
  params.require(:book).permit(:title, :author, :summary, :picture)
   
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	comment = Comment.new(permitted_params)
  	if comment.save
       flash[:notice]= "A new User has been successfully created."
  		redirect_to :back
  	else
      flash[:error] = comment.errors.full_messages.to_sentence
  		redirect_to :back
  	end
  end

def destroy
    @comment=Comment.find(params[:id])
	@comment.destroy
	redirect_to :back
end


  private
   def permitted_params
  params.require(:comment).permit(:book_id, :user_id, :comment)
   
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update, :destroy]

  def index
    @user=User.all
  end

  def new
    @user=User.new
  end

  def show
    @user=User.find(params[:id])
  end  

  def create
    @user=User.new(permitted_params)
   if @user.save
        flash[:notice]= "A new User has been successfully created."
     redirect_to users_path

      else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to new_user_path 
      end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    if @user.update(permitted_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        flash[:error] = @user.errors.full_messages.to_sentence
        redirect_to edit_user_path(@user)
      end
  end

  def destroy
        @user.destroy
    redirect_to :back
  end

  private

  def set_user
    @user=User.find(params[:id])
    #@book=@user.books
  end

 def permitted_params
  params.require(:user).permit(:first_name, :last_name, :username, :picture)
   
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/delete_helper.rb
module DeleteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<style>

h1 {
  text-align : center;
  border-radius: 1px;
  }

  .container{ 
  margin-left: 520px;
  position: absolute;
  width:520px;
  -webkit-box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
  box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
}

.bg_img{
  position: absolute;
  display: inline-block;
  height: auto;
  margin-left: 300px;
  margin-top: 30px;
  width: 1200px;
  -webkit-filter:blur(5px);
  -moz-filter: blur(3px); 
  -o-filter: blur(3px); 
  -ms-filter: blur(3px); 
  filter: blur(3px);
}

.field{text-align: center;}

.actions{text-align: center;}

.link_to{text-align: center;
  font-size: 100%;
  text-shadow: 0.07em 0.3em 0.9em #333;}

</style>


<h1>Editing Book</h1>

<br>
<%- if flash[:error].present? -%>
	<div style="text-align:center;color: white;padding:5px;background-color:red;margin-bottom:12px;" >
  <%= flash[:error]%>
  	</div>
<%- end -%>

<div class="bg_img">
  <%= image_tag("url.jpeg") %>
</div>

<div class="container">

<%= form_for(@book, url: user_book_path(@user, @book, method: :put)) do |f| %>
<div class="field"><br>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field"><br>
    <%= f.label :author %>
    <%= f.text_field :author %><br>
  </div>
  <div class="field"><br>
    <%= f.label :summary %>
    <%= f.text_area :summary %><br>
  </div>

  <div class="field"><br>
    <%= f.label :picture %>
    <%= f.text_field :picture %><br>
  </div><br>
  <div class="actions">
    <%= f.submit  %><br><br>
  </div>
<%- end -%>
<div class="link_to"><%= link_to 'Show', user_book_path(@user, @book) %>&nbsp&nbsp&nbsp
<%= link_to 'Back', :back %>
</div>
<br><br>
</div>

app/views/books/index.html.erb
<h1>Home page</h1><br>



<div class="link_to">

<%= link_to 'New Book', new_user_book_path%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to 'Back', users_path%>


<div class="content">
</div>

<% if flash[:notice] %>
    <div class="notice" style="text-shadow: 0.07em 0.3em 0.9em #333; text-align:center;color: green; padding:5px; margin-bottom:12px;">
      <%= flash[:notice] %>
    </div>
  <% end %>

<hr>
<div class="col">
<table>
  <tr> 
    <th>ID</th>
    <th>Title</th>
    <th>Author</th>
    <th>Summary</th>
    <th>Image</th>
  </tr>
  
<% @books.each do |book| %>
   <tr>
    <td><%= book.id %></td>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.summary %></td>
    <td><div id="bg_img"><%= image_tag book.picture %></div></td>
    
   
     <td>
 <div class="link_to">
    <%= link_to 'Show', user_book_path(@user, book) %>&nbsp&nbsp&nbsp
    <%= link_to 'Edit', edit_user_book_path(@user, book) %>&nbsp&nbsp&nbsp
    <%= link_to 'Remove', user_book_path(@user,book), method: :delete, data: { confirm: "Are you sure?" } %>
  
  </td>
</div>

 </tr>

<% end %>
</table>
</div>
</div>

app/views/books/new.html.erb
<style>
h1 {
  text-align : center;
  border-radius: 1px;
  }

.container{ 
  margin-left: 520px;
  position: absolute;
  -webkit-box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
  box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
  }

.bg_img{
  position: absolute;
  display: inline-block;
  height: auto;
  margin-left: 300px;
  margin-top: 30px;
  width: 1200px;
  -webkit-filter:blur(5px);
  -moz-filter: blur(3px); 
  -o-filter: blur(3px); 
  -ms-filter: blur(3px); 
  filter: blur(3px);
}

  table {text-align: center;
    width: 100%;
    background: #eee;
    border: 1px solid #eee;
    -column-gap: 40px;
    }

  #context{text-align: center;}

  .link_to{text-align: center;
  font-size: 100%;
  text-shadow: 0.07em 0.3em 0.9em #333;}

</style>

<br>

<h1>Add a Book</h1>
<br>  

<div class="bg_img">
  <%= image_tag("url.jpeg") %>
</div>

<div class ="container">
  <br>
<%- if flash[:error].present? -%>
<div style="text-align:center;color: white;padding:5px;background-color:red;margin-bottom:12px;" >
  <%= flash[:error]%>
</div>
<%- end -%>
<br><br>
<div id="context" style=text-align=center>
<%= form_for @book, {url: user_books_path} do |f|%>
<%= f.text_field :title, placeholder: 'Title name*'%><br/><br>
<%= f.text_field :author, placeholder: 'Author Name*'%><br/><br>
<%= f.text_area :summary, placeholder: 'summary'%><br/><br>
<%= f.text_field :picture, placeholder: 'paste image url'%><br/><br>
<%= f.submit%>
<%- end -%>

<div class="link_to">
  <%= link_to 'Back', user_books_path %>
</div>
</div>
<br><br>
</div>

app/views/books/show.html.erb
<script type="text/javascript">
$(document).ready(function(){
  $('.likes').click(function(){
    var e = $(this);
    if (e.html()=="Like"){
      e.html('Unlike');  
    }else{
      e.html('Like');
    }
  });
});
</script>



<style>

h1 {
  text-align : center;
  border-radius: 1px;
  }

.bg_img{
  position: absolute;
  display: inline-block;
  height: auto;
  margin-left: 400px;
  margin-top: 140px;
  width: 1200px;
  -webkit-filter:blur(5px);
  -moz-filter: blur(3px); 
  -o-filter: blur(3px); 
  -ms-filter: blur(3px); 
  filter: blur(3px);
}

.container{ 
  margin-top:20px;
  width:550px;
  -webkit-box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
  box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
}

.context{
  position: absolute;
  webkit-box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
  box-shadow: 0 0 5px 2px rgba(0, 0, 0, .5);
  margin: 10px 350px;
  border: 1px solid #eee;
  vertical-align: top;
  width:800px;
  font-size: 100%;
}

 .content{margin:10px 5px;
  white-space: nowrap;
  border-left:1em solid transparent;
  border-right:1em solid transparent;
  text-overflow: ellipsis;
}

#n_user{text-align: center;}

.link_to{text-align: center;
  font-size: 100%;
  text-shadow: 0.07em 0.3em 0.9em #333;}

.cont_f{
  word-break: break-word;
  white-space: normal;
  width:230px;
  display: inline-block;
  text-align: justify;
  white-space: -webkit-pre-wrap;
margin:0 50px;
letter-spacing: 1.5px;
line-height: 22px;}

.cont{padding-top: -90px;
 display:inline-block;
}

.user{margin-left: 20px;
display:inline-block;
}

#img_user{width:18px;
  display:inline-block;
height:auto;}

#img{
  width: 200px;
height: 100%;
box-shadow: 10px 10px 5px #ccc; 
-moz-box-shadow: 10px 10px 20px 10px #ccc; 
-webkit-box-shadow: 10px 10px 20px 10px #ccc; 
-khtml-box-shadow: 10px 10px 20px 10px #ccc;
display: inline-block;
}

</style>


<h1>Showing Book</h1>

<br>

<div class="bg_img">
  <%= image_tag("url.jpeg") %>
</div>

<div class="context">

<div class="container">
<br>
<div class="link_to"><%= link_to 'Back', user_books_path(@user) %>
</div><br>

<div class="content">

<div id="img">

    <%= image_tag @book.picture, class: "blur" %>
  </div>



<div class="cont_f">

<b>Name:</b> <%= @user.first_name + ' ' + @user.last_name %><br>

<b>Book Title:</b> <%= @book.title %><br>

<b>Author:</b> <%= @book.author %><br>

<b>Summary:</b> <%= @book.summary %><br>

</div>
</div><br>

</div>
<br><br>

  <div id="com" style="margin: 10px 130px;">
    <%- @comments.each do |comment| %>
     <div class='commentContainer'>
      <div id="img_user">
        <%= image_tag comment.user.picture %>
      </div>
     <div class='user'>

       <b><%= comment.user.first_name%> says:  </b>
     
        <%= comment.comment %>&nbsp&nbsp&nbsp&nbsp
        <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } %> <br>

        
            <div>
                 <a href="javascript:void(0)" class="likes">Like</a> 
                 
            </div>
        
      </div><hr>
    </div>
    <%- end -%>
    <h5>Select User below to comment</h5>
    <%= form_for @comment do |f| %>
    <%= f.select :user_id, User.all.collect {|u| [ u.first_name, u.id ] }%>

<br>
    <%= f.hidden_field :book_id, value: @book.id%>
    <%= f.text_area :comment%>
    <%= f.submit 'Comment'%>
    <%- end -%>
    <br>
  </div><br>
</div><br><br>
<br><br><br>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<style>
h1 {
  background: #eee;
  text-align : center;
  border-radius: 1px;
  
  }
#n_user{text-align: center;}
  table {text-align: center;
    width: 100%;
    background: #eee;
    -webkit-column-count:5;
    border: 1px solid #eee;
    -column-gap: 40px;
    }

#links{text-align:center;}

</style>

<h1>Comments on <%= @book.title %></h1><br>
<div id="links">

<%= link_to 'New Book', new_user_book_path%>

</div>

<hr>

<table>
<% @books.each do |book| %>
 <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Author</th>
    <th>Summary</th>
    <th>Image url</th>
  </tr>
  <tr>
    <td><%= book.id %></td>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.summary %></td>
    <td><%= book.picture %></td>
    
     <td>
 
    <%= link_to 'Show', user_book_path(@user, book) %>&nbsp&nbsp&nbsp
    <%= link_to 'Edit', edit_user_book_path(@user, book) %>&nbsp&nbsp&nbsp
    <%= link_to 'Remove', user_book_path(@user,book), method: :delete, data: { confirm: "Are you sure?" } %></td>
 </tr>
<% end %>
</table><br>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Editing User</h1>
<br>

<div class="main">

<div class="edit_user_img">
    <%= image_tag @user.picture%>
</div>


<div class='edit_container'>
  
<%- if flash[:error].present? -%>
	<div style="text-align:center;color: white;padding:5px; margin-left:80px; position: absolute;" >
  <%= flash[:error]%>
  	</div>
<%- end -%>

<br>

<%= form_for(@user) do |f| %>
<div class="field"><br>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field"><br>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %><br>
  </div>
  <div class="field"><br>
    <%= f.label :username %>
    <%= f.text_field :username %><br>
  </div>

    <div class="field"><br>
    <%= f.label :picture %>
    <%= f.text_field :picture %><br>
  </div><br>
  <div class="actions">
    <%= f.submit  %><br><br>
  </div>
<%- end -%>

<div class="link_to">
  <%= link_to 'Show', user_path %>&nbsp&nbsp&nbsp
<%= link_to 'Back', users_path %>
</div>

 <br><br><br>

</div>
</div>

app/views/users/index.html.erb
<h1>Home page</h1><br>

<div class="cont">

<% if flash[:notice] %><br>
    <div class="notice" style="text-shadow: 0.07em 0.3em 0.9em #333; text-align:center; color: green; 
      padding:5px; margin-left:21%; position: absolute;">
      <%= flash[:notice] %>
    </div>
  <% end %>

<div class="link">

<%= link_to 'New User', new_user_path %>

</div>

<hr><table>
 <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Username</th>
    <th>Image</th>
    <th></th>
  </tr>

<% @user.each do |user| %>

   <div class="links">
  <tr>
    <td><%= user.id %></td>
    <td><%= user.first_name + ' ' +user.last_name %></td>
    <td><%= user.username %></td>
    <td><%= image_tag user.picture, style: "width: 50%; height: auto;" %></td>
    

     <td>
      <div class="link_to" >
    <%= link_to 'View Books', user_books_path(user) %> 
    <%= link_to 'Show', user %> 
    <%= link_to 'Edit', edit_user_path(user) %> 
    <%= link_to 'Remove', user, method: :delete, data: { confirm: "Are you sure?" } %> 
  </td>
  </div
 </tr>

<% end %>
</div>
</table>
</div>

app/views/users/new.html.erb
<h1>User Registration</h1>

<br>

<div class="container">

<div class="bg_img">
  <%= image_tag("user-img.png") %>
</div>

<%- if flash[:error].present? -%>
<div style="text-align:center;color: red; margin-left:5%; margin-top: -0.5%; position: absolute;" >
  <%= flash[:error]%>
</div>
<%- end -%>
<br><br>
<div class="context" style=text-align=center>
<%= form_for @user, {url: users_path} do |f|%>
<%= f.text_field :first_name, placeholder: 'First Name*'%><br/><br>
<%= f.text_field :last_name, placeholder: 'Last Name'%><br/><br>
<%= f.text_field :username, placeholder: 'username'%><br/><br>
<%= f.text_field :picture, placeholder: 'paste image url'%><br/><br>
<%= f.submit%>
<%- end -%>

<div class="link_to">
<%= link_to 'Back', users_path %>
</div>

</div> <br><br>

</div>

app/views/users/show.html.erb
<h3><%= @user.first_name.capitalize %>'s Information</h3>

<hr>
<div class="container">
	<br><br />
<div class="link_to">
<%= link_to 'Back', users_path %>&nbsp&nbsp&nbsp
    <%= link_to 'Edit', edit_user_path(@user) %><br><br>
</div>

<div class="content">

<div class="show_img">

    <%= image_tag @user.picture %>
  </div>

</div>

<br>

<div class="field">

<b>First Name:</b> <%= @user.first_name %><br>

<b>Last Name:</b> <%= @user.last_name %><br>

<b>Username:</b> <%= @user.username %><br>

</div> <br><br><br><br>

</div><br><br>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>